#!/usr/bin/env bash
# Day 16, Step 3 — the five services from ECR, onto EKS, with the ticket layer wired.
#
# k8s/aws/*.yaml are GENERATED from k8s/*.yaml: the image line becomes the ECR URL with the
# tag kind runs (the one 153 pushed), kind's NodePort front doors are dropped (no host
# mapping on EKS; traffic arrives by port-forward — 164), nothing else changes. They are
# committed so `diff -r k8s k8s/aws` shows the whole difference between the two clusters:
# it should be the image lines and nothing else (CORRECTIONS-DAY16 D2).
#
#   ./scripts/163-eks-deploy.sh            render, deploy, wire secrets, verify
#   ./scripts/163-eks-deploy.sh --render   only write k8s/aws/ (and show the diff)
export KUBE_CONTEXT=aws-lab
source "$(dirname "$0")/lib.sh"
require_aws; require_cluster
cd "$LAB_ROOT" || exit 1
REG=$(aws_registry)
SERVICES=(activation egift settlement incident-bot remediator)
KIND="kind-$CLUSTER_NAME"

live_tag() {  # what ECR holds for a service = what kind ran when 153 pushed
  aws ecr describe-images --repository-name "bhn-sim/$1" --query 'imageDetails[].imageTags[]' --output text 2>/dev/null | tr '\t' '\n' | grep -vx latest | sed -n 1p
}

step "Rendering k8s/aws/ from k8s/ (image lines only; NodePort front doors dropped)"
mkdir -p k8s/aws
for svc in "${SERVICES[@]}"; do
  TAG=$(live_tag "$svc"); [[ -n "$TAG" ]] || die "no image for $svc in ECR — ./scripts/153-aws-ecr-push.sh"
  python3 - "k8s/$svc.yaml" "k8s/aws/$svc.yaml" "$svc" "$REG/bhn-sim/$svc:$TAG" <<'PY'
import re, sys
src, dst, svc, image = sys.argv[1:]
docs = open(src).read().split("\n---\n")
out = []
for d in docs:
    if "type: NodePort" in d:            # kind's localhost front door; EKS has no host mapping
        continue
    d = re.sub(r"^(\s*image:\s*)%s:\S+" % re.escape(svc), r"\g<1>%s" % image, d, flags=re.M)
    out.append(d)
text = "\n---\n".join(out)
hdr = "# GENERATED by scripts/163-eks-deploy.sh from k8s/%s.yaml — edit THAT file. Only the image line differs (and kind's NodePort door is gone).\n" % svc
open(dst, "w").write(hdr + text)
PY
  ok "k8s/aws/$svc.yaml  image -> $REG/bhn-sim/$svc:$TAG"
done
IMG=$(diff -r k8s k8s/aws 2>/dev/null | grep -cE '^> .*image: ' || true); ALL=$(diff -r k8s k8s/aws 2>/dev/null | grep -cE '^[<>] ' || true)
say "  diff -r k8s k8s/aws: $IMG image lines changed, $ALL lines differ in total (the rest: the header comment and the dropped NodePort docs)"
[[ "${1:-}" == "--render" ]] && { ok "rendered only"; exit 0; }

step "Secrets the services need — copied from kind, never through a file"
# ai-keys (Day 9): the same key, piped cluster-to-cluster; it touches no disk and no log.
if kubectl --context "$KIND" get secret ai-keys -n "$PAYMENTS_NS" >/dev/null 2>&1; then
  kubectl --context "$KIND" get secret ai-keys -n "$PAYMENTS_NS" -o json \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); d["metadata"]={"name":d["metadata"]["name"],"namespace":d["metadata"]["namespace"]}; print(json.dumps(d))' \
    | k apply -f - >/dev/null && ok "secret/ai-keys copied kind -> aws-lab (contents not shown)"
else
  warn "no secret/ai-keys on kind — the bot runs without drafts; KUBE_CONTEXT=aws-lab ./scripts/90-ai-secret.sh to add one here"
fi

step "Deploying (context aws-lab)"
for svc in "${SERVICES[@]}"; do k apply -f "k8s/aws/$svc.yaml" >/dev/null && ok "$svc"; done
k apply -f k8s/alerts.yaml >/dev/null && ok "PrometheusRule activation-alerts (same rules as kind)"
k apply -f k8s/grafana-datasource-tempo.yaml >/dev/null && ok "Grafana Tempo datasource ConfigMap"
"$LAB_ROOT/scripts/09-grafana-dashboards.sh" >/dev/null 2>&1 && ok "dashboards provisioned (09, via KUBE_CONTEXT=aws-lab)" || warn "09-grafana-dashboards.sh failed — run it by hand: KUBE_CONTEXT=aws-lab ./scripts/09-grafana-dashboards.sh"

step "Rollouts"
for d in activation egift incident-bot remediator; do
  k rollout status deploy/$d -n "$PAYMENTS_NS" --timeout=240s >/dev/null && ok "deploy/$d" || { k get pods -n "$PAYMENTS_NS" -l app=$d | sed 's/^/  /'; warn "deploy/$d not ready — describe a pod: ImagePullBackOff = ECR/arch (153 --verify), Pending = capacity (160 status)"; }
done
PV=$(k get pvc incident-bot-data -n "$PAYMENTS_NS" -o jsonpath='{.status.phase}' 2>/dev/null || true)
[[ "$PV" == Bound ]] && ok "incident-bot's PVC Bound — an EBS volume, provisioned by the CSI driver through Pod Identity (kind had local-path)" || warn "PVC incident-bot-data is '${PV:-missing}' — the EBS CSI add-on or its pod identity (161's add-on list)"
k get cronjob settlement -n "$PAYMENTS_NS" >/dev/null 2>&1 && ok "cronjob/settlement (next tick within 5 min)"

step "Wiring the ticket layer (the same scripts, KUBE_CONTEXT=aws-lab)"
"$LAB_ROOT/scripts/100-enrich-config.sh" 2>&1 | grep -E '^\s*(ok|warn|FAIL| +(metrics|deploys|logs) )' | sed 's/^/  /' || true
"$LAB_ROOT/scripts/120-remediator-config.sh" 2>&1 | grep -E '^\s*(ok|warn|FAIL)' | tail -4 | sed 's/^/  /' || true

step "Proof: the whole nervous system, on a cloud it has never seen"
sleep 20
UP=$(promql 'count(up{namespace="payments"} == 1)' | python3 "$LAB_ROOT/tools/promjson.py" value '{:.0f}' 2>/dev/null || echo 0)
say "  Prometheus targets UP in payments: $UP (expect 4 — activation, egift, incident-bot, remediator; settlement is a job, via pushgateway)"
bot_get /healthz | grep -c ok >/dev/null && ok "incident-bot answering through the API proxy" || warn "bot not answering yet"
alertmanager_get /api/v2/status | grep -c 'incident-bot' >/dev/null && ok "Alertmanager -> incident-bot route live (from kps-values.yaml, unchanged)" || warn "Alertmanager route not visible yet"
rem_get /healthz | grep -c ok >/dev/null && ok "remediator answering" || warn "remediator not answering yet"
LG=$(aws logs describe-log-streams --log-group-name /bhn-sim/containers --query 'length(logStreams)' --output text 2>/dev/null || echo 0)
(( LG > 0 )) && ok "CloudWatch: /bhn-sim/containers has $LG stream(s) — Fluent Bit ships, Pod Identity works" || warn "no CloudWatch streams yet — give it a minute, then: aws logs describe-log-streams --log-group-name /bhn-sim/containers"
echo
say "  Zero application changes. Zero manifest changes beyond the image line. That portability is Kubernetes doing its job."
ok "Next: ./scripts/164-eks-traffic.sh (terminal 2), then KUBE_CONTEXT=aws-lab GRAFANA_PORT=3001 ./scripts/06-grafana.sh (terminal 3), then ./scripts/165-eks-drill.sh"
